var critterGrammar = {
        "origin":["#adj-combo# #animal#", "#adj-combo# #adj-location#-#animal#"],
        "adj-combo":[
                        "#adj-size# #adj-color# #adj-texture# #adj-location#", 
                        "#adj-size# #adj-texture# #adj-location#", 
                        "#adj-size# #adj-doing# #adj-location#", 
                        "#adj-size# #adj-color# #adj-texture#", 
                        "#adj-color# #adj-texture# #adj-location#", 
                        "#adj-texture# #adj-location#",
                        "#adj-color# #adj-texture#", 
                        "#adj-size# #adj-location#", 
                        "#adj-size# #adj-doing#", 
                        "#adj-size# #adj-texture#", 
                        "#adj-texture# #adj-location#"
                    ],
        "adj-texture":["fluffy", "fuzzy", "prickled", "spikey"],        
        "gem-color":[
                "diamond", "sapphire", "topaz", "emerald", "ruby"
        ],
        "metallic-color":[
                                "gold", "silver", "copper", "bronze", "platinum","brass",
                                "#warm-color# copper", "#warm-color# gold", "#warm-color# bronze", "#warm-color# brass",
                                "#cold-color# silver", "#cold-color# platinum"
                         ],
        "primary-color":["red", "blue", "yellow"],
        "secondary-color":["purple", "green", "violet"],
        "warm-color":["red", "yellow", "orange"],
        "cold-color":["blue", "violet", "green"],
        "brown-color":["brown", "taupe", "tan", "sepia", "sand", "coffee", "chocolate", "smoke", "wheat", "amber"],
        "normal-color":[
                                "#primary-color#", "#secondary-color#",
                                "pink", "purple", "lavender", "orchid",
                                "maroon", "rose", "rust", "cerise", "fuchsia", "peach", "mauve", "wine", "magenta",
                                "teal", "aqua", "turquoise", "indigo", "azure", "cyan",
                                "olive", "puce", "sage",
                                "lemon",
                                "white", "black", "grey",
                                "#brown-color#"
                       ],
        "adj-doing" : ["jumping", "burrowing", "flying", "screaming", "dancing"],
        "adj-size" : ["miniature","giant"],
        "adj-location" :["mountain", "river", "plains-dweller","space-faring", "komodo", "sea", "polar", "arctic", "guinea", "prairie"],
        "adj-color" :[
                "#normal-color#",
                "#metallic-color#",
                "#gem-color#",
                "#primary-color#-#secondary-color#",
                "#normal-color# pearl",
                "#normal-color# #gem-color#",
                "royal #normal-color#",
                "sandy #brown-color#",
                "sea #cold-color#",
                "frost #cold-color#",
                "vivid #normal-color#",
                "white #brown-color#",
                "black #brown-color#",
                "antique #normal-color#",
                "antique #metallic-color#",
                "bright #normal-color#",
                "dark #normal-color#",
                "deep #normal-color#"
        ],
        "animal":[
                'aardvark', 'albatross', 'alligator', 'alpaca', 'ant', 'anteater', 'antelope', 'ape', 'armadillo', 'baboon', 
                'badger', 'barracuda', 'bat', 'batfish', 'bear', 'beaver', 'bee', 'beetle', 'bison', 'boar', 
                'buffalo', 'butterfly', 'camel', 'capybara', 'caribou', 'cassowary', 'cat', 'caterpillar', 'cattle', 'cavefish', 
                'centipede', 'chamois', 'cheetah', 'chicken', 'chimpanzee', 'chinchilla', 'chough', 'clam', 'cobra', 'cockroach', 
                'cod', 'cormorant', 'coyote', 'crab', 'crane', 'crocodile', 'crow', 'curlew', 'deer', 'dinosaur', 
                'dog', 'dogfish', 'dolphin', 'donkey', 'dotterel', 'dove', 'dragonfly', 'duck', 'dugong', 'dunlin', 'dragon',
                'eagle', 'echidna', 'eel', 'egret', 'eland', 'elephant', 'elephant-seal', 'elk', 'emu', 'falcon', 
                'ferret', 'finch', 'fish', 'flamingo', 'fly', 'fox', 'fowl', 'frog', 'gaur', 'gazelle', 'gerbil', 
                'giraffe', 'gnat', 'gnu', 'goat', 'goose', 'gorilla', 'goshawk', 
                'grasshopper', 'grouse', 'guanaco', 'gull', 'hamster', 'hare', 'hawk', 'hedgehog', 
                'heron', 'herring', 'hippopotamus', 'hornet', 'horse', 'hound', 'human', 'hummingbird', 'hyena', 'ibex', 
                'ibis', 'jackal', 'jaguar', 'jay', 'jellyfish', 'kangaroo', 'kingfisher', 'koala', 'kookabura', 
                'kouprey', 'kudu', 'lapwing', 'lark', 'lemur', 'leopard', 'lion', 'llama', 'lobster', 'locust', 
                'loris', 'louse', 'lyrebird', 'magpie', 'mallard', 'manatee', 'mandrill', 'mantis', 'marmoset', 'marten', 
                'meerkat', 'mink', 'mole', 'mongoose', 'monkey', 'moose', 'mosquito', 'moth', 'mouse', 'mule', 
                'narwhal', 'newt', 'nightingale', 'octopus', 'okapi', 'opossum', 'oryx', 'ostrich', 'otter', 'owl', 
                'ox', 'oyster', 'panda', 'panther', 'parrot', 'partridge', 'peafowl', 'pelican', 'penguin', 'pheasant', 
                'pig', 'pigeon', 'pony', 'porcupine', 'porpoise', 'quail', 'quelea', 'quetzal', 
                'rabbit', 'raccoon', 'rail', 'ram', 'rat', 'raven', 'reindeer', 'rhinoceros', 'robin', 'rook', 
                'salamander', 'salmon', 'sand-dollar', 'sandpiper', 'sardine', 
                'scorpion', 'urchin', 'seal', 'shark', 'sheep', 'shrew', 'skunk', 'snail', 
                'snake', 'sparrow', 'spider', 'spoonbill', 'squid', 'squirrel', 'starling', 'stingray', 'stinkbug', 'stork', 
                'swallow', 'swan', 'tapir', 'tarsier', 'termite', 'tiger', 'toad', 'treehoppper', 'trout', 'turkey', 
                'turtle', 'vicuña', 'viper', 'vulture', 'wallaby', 'walrus', 'wasp', 'water-buffalo', 'weasel', 'whale', 
                'wildcat', 'wolf', 'wolverine', 'wombat', 'woodcock', 'woodpecker', 'worm', 'wren', 'yak', 'zebra'
                ]
    };
