var critterGrammar = {
        "origin":["#adj-combo# #animal#"],
        "adj-combo":[
                        "#adj-size# #adj-color# #adj-texture# #adj-location#", 
                        "#adj-size# #adj-texture# #adj-location#", 
                        "#adj-size# #adj-doing# #adj-location#", 
                        "#adj-size# #adj-color# #adj-texture#", 
                        "#adj-color# #adj-texture# #adj-location#", 
                        "#adj-texture# #adj-location#",
                        "#adj-color# #adj-texture#", 
                        "#adj-size# #adj-location#", 
                        "#adj-size# #adj-doing#", 
                        "#adj-size# #adj-texture#", 
                        "#adj-texture# #adj-location#"
                    ],
        "adj-texture":["fluffy", "fuzzy", "prickled", "spikey"],
        "adj-color" :["red", "lilac", "miniature", "giant"],
        "adj-doing" : ["jumping","burrowing"],
        "adj-size" : ["minature","giant"],
        "adj-location" :["mountain", "river", "plains-dweller","space-faring"],
        "animal":[
                'aardvark', 'albatross', 'alligator', 'alpaca', 'ant', 'anteater', 'antelope', 'ape', 'armadillo', 'baboon', 
                'badger', 'barracuda', 'bat', 'batfish', 'bear', 'beaver', 'bee', 'beetle', 'bison', 'boar', 
                'buffalo', 'butterfly', 'camel', 'capybara', 'caribou', 'cassowary', 'cat', 'caterpillar', 'cattle', 'cavefish', 
                'centipede', 'chamois', 'cheetah', 'chicken', 'chimpanzee', 'chinchilla', 'chough', 'clam', 'cobra', 'cockroach', 
                'cod', 'cormorant', 'coyote', 'crab', 'crane', 'crocodile', 'crow', 'curlew', 'deer', 'dinosaur', 
                'dog', 'dogfish', 'dolphin', 'donkey', 'dotterel', 'dove', 'dragonfly', 'duck', 'dugong', 'dunlin', 
                'eagle', 'echidna', 'eel', 'egret', 'eland', 'elephant', 'elephant-seal', 'elk', 'emu', 'falcon', 
                'ferret', 'finch', 'fish', 'flamingo', 'fly', 'fox', 'frog', 'gaur', 'gazelle', 'gerbil', 
                'giant-panda', 'giraffe', 'gnat', 'gnu', 'goat', 'goldfinch', 'goldfish', 'goose', 'gorilla', 'goshawk', 
                'grasshopper', 'grouse', 'guanaco', 'guinea-fowl', 'guinea-pig', 'gull', 'hamster', 'hare', 'hawk', 'hedgehog', 
                'heron', 'herring', 'hippopotamus', 'hornet', 'horse', 'hound', 'human', 'hummingbird', 'hyena', 'ibex', 
                'ibis', 'jackal', 'jaguar', 'jay', 'jellyfish', 'kangaroo', 'kingfisher', 'koala', 'komodo-dragon', 'kookabura', 
                'kouprey', 'kudu', 'lapwing', 'lark', 'lemur', 'leopard', 'lion', 'llama', 'lobster', 'locust', 
                'loris', 'louse', 'lyrebird', 'magpie', 'mallard', 'manatee', 'mandrill', 'mantis', 'marmoset', 'marten', 
                'meerkat', 'mink', 'mole', 'mongoose', 'monkey', 'moose', 'mosquito', 'moth', 'mouse', 'mule', 
                'narwhal', 'newt', 'nightingale', 'octopus', 'okapi', 'opossum', 'oryx', 'ostrich', 'otter', 'owl', 
                'ox', 'oyster', 'panda', 'panther', 'parrot', 'partridge', 'peafowl', 'pelican', 'penguin', 'pheasant', 
                'pig', 'pigeon', 'polar-bear', 'pony', 'porcupine', 'porpoise', 'prairie-dog', 'quail', 'quelea', 'quetzal', 
                'rabbit', 'raccoon', 'rail', 'ram', 'rat', 'raven', 'red deer', 'red panda', 'red-deer', 'red-panda', 
                'reindeer', 'rhinoceros', 'robin', 'rook', 'salamander', 'salmon', 'sand dollar', 'sand-dollar', 'sandpiper', 'sardine', 
                'scorpion', 'sea-lion', 'sea-urchin', 'seahorse', 'seal', 'shark', 'sheep', 'shrew', 'skunk', 'snail', 
                'snake', 'sparrow', 'spider', 'spoonbill', 'squid', 'squirrel', 'starling', 'stingray', 'stinkbug', 'stork', 
                'swallow', 'swan', 'tapir', 'tarsier', 'termite', 'tiger', 'toad', 'treehoppper', 'trout', 'turkey', 
                'turtle', 'vicuña', 'viper', 'vulture', 'wallaby', 'walrus', 'wasp', 'water-buffalo', 'weasel', 'whale', 
                'wildcat', 'wolf', 'wolverine', 'wombat', 'woodcock', 'woodpecker', 'worm', 'wren', 'yak', 'zebra'
                ]
    };
